# Generated by Django 3.1.7 on 2021-04-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django101', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
